# 엑셀 포트폴리오 리포트 생성기 설정

# 엑셀 시트 설정
excel:
  # 시트명
  sheets:
    dashboard: '요약 대시보드'
    holdings: '상세 구성'
    timeline: '시간 흐름'
    ai_news: 'AI & 뉴스'

  # 셀 위치 (KPI 카드, 차트 앵커 등)
  positions:
    kpi_start_row: 2
    kpi_start_col: 2
    chart_start_row: 10
    chart_start_col: 2

  # 차트 스타일
  chart_style:
    colors:
      primary: '#2E86AB'
      secondary: '#A23B72'
      success: '#F18F01'
      warning: '#C73E1D'
      info: '#6C757D'

    fonts:
      title: '맑은 고딕'
      body: '맑은 고딕'
      size_title: 14
      size_body: 11

# AI 설정
ai:
  openai:
    model: 'gpt-4'
    max_tokens: 1000
    temperature: 0.7

  anthropic:
    model: 'claude-3-sonnet-20240229'
    max_tokens: 1000
    temperature: 0.7

# 파일 경로
paths:
  data_dir: 'data'
  reports_dir: 'reports'
  template_file: 'reports/template.xlsx'
  output_file: 'reports/portfolio_report.xlsx'
  archive_dir: 'reports/archive'
